name: Publication of qualifying release to PyPI

on:
  release:
    types: [published]

jobs:
  build:
      name: Publish release to PyPI (testing)
      #env:
      #  TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      #  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      runs-on: ubuntu-latest
      steps:

          # Check out the commit containing this workflow file.
          - name: checkout repo
            uses: actions/checkout@v2
         
          # Run the custom action
          - name: custom action
            uses: rendinam/publicator-action@master
            id: custom_action_0
