name: Automatic publication of release to PyPI
on:
    release:
        types: [published]

jobs:
    build:
        name: Publish release to PyPI (testing)
        runs-on: ubuntu-latest
        steps:
          # Check out the commit containing this workflow file.
          - uses: actions/checkout@v2
          - name: git log
            run: git log
          - name: Setup up python 3.x
            uses: actions/setup-python@v1
            with:
                python-version: '3.x'
                architecture: 'x64'
          - name: python version
            run: python --version
          - name: install package
            run: pip install .
          - name: examine version and publish if criteria met
            run: python -c 'import testertron; print(testertron.__version__)'
          - name: install publication deps
            run: pip install twine
          - name: prepare for publication
            run: git clean -fxd
                 python setup.py build sdist --format=gztar
          - name: examine tag and publish if criteria met
            run: echo $GITHUB_REF
