name: Publication of qualifying release to PyPI

on:
  release:
    types: [published]

jobs:
  build:
      name: Publish release to PyPI (testing)
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      runs-on: ubuntu-latest
      steps:

          #- name: Setup up python 3.x
          #  uses: actions/setup-python@v1
          #  with:
          #    python-version: '3.x'
          #    architecture: 'x64'

          # Check out the commit containing this workflow file.
          - name: checkout repo
            uses: actions/checkout@v2
          
          - name: custom action
            uses: rendinam/publicator-action@master
            id: custom_action_0
