name: Automatic publication of release to PyPI
on:
    release:
        types: [published]

jobs:
    build:
        name: Publish release to PyPI (testing)
        env:
            TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        runs-on: ubuntu-latest
        steps:

        - name: Setup up python 3.x
          uses: actions/setup-python@v1
            with:
              python-version: '3.x'
              architecture: 'x64'

        # Check out the commit containing this workflow file.
        - uses: actions/checkout@v2

        - name: env
          run: env

        #- name: custom action
        #- id: custom_action_0
        #- uses: rendinam/publicator-action@master
        #- with:
        #-     who-to-greet: "Greetee"

        #- name: Get custom action's output
        #- run: echo "The output was ${{ steps.custom_action_0.outputs.time }}"

        - name: examine tag and publish if criteria met
          run: echo $GITHUB_REF

        - name: git log
          run: git log

        - name: python version
          run: python --version

        # Installation smoke test
        - name: install package
          run: pip install .

        - name: install publication deps
          run: pip install twine

        - name: prepare for publication 1
          run: git clean -fxd

        - name: prepare for publication 2
          run: python setup.py build sdist --format=gztar

        - name: publish to PyPI [testing]
          run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
