name: Automatic publication of release to PyPI
on:
    release:
        types: [published]

jobs:
    build:
        name: Publish release to PyPI (testing)
        runs-on: ubuntu-latest
        steps:
          # Check out the commit containing this workflow file.
          - uses: actions/checkout@v2
          - name: List
            run: ls -alth
          - name: pwd
            run: pwd
          - name: Setup up python 3.x
            uses: actions/setup-python@v1
            with:
                python-version: '3.x'
                architecture: 'x64'
          - name: python version
            run: python --version
          - name: install package
            run: pip install .
          - name: run test
            run: testertron
          - name: examine version
            run: export VERSION=$(python -c 'import testertron; print(testertron.__version__)')
          - name: print version from var
            run: echo $VERSION
          - name: env var
            run: echo $GITHUB_REF
